services:
  - type: web
    name: personal-academic-management
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@portfolio.local
      - key: ADMIN_PASSWORD
        value: AdminPassword@123
